site_name: HPO Workshop
site_url: https://github.com/P2GX/HpoWorkshop
site_description: Introduction to the Human Phenotype Ontology (HPO) and HPO Applications

theme:
  name: material
  logo: img/hpo-logo.png      # Logo in the top-left navigation bar
  favicon: img/favicon.png
  palette:
    # Scientific/Medical Blue theme
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs          # Top-level navigation
    - navigation.sections      # Grouped sidebar
    - navigation.expand        # Keep sidebar open
    - content.code.copy        # Copy buttons for exercises
    - toc.follow               # Table of contents follows scroll
    - search.highlight     # Highlights searched terms on the page
    - search.suggest       # Shows search suggestions in the dropdown
    - search.share         # Generates a link to the specific search

markdown_extensions:
  - admonition                 # For Exercise/Hint boxes
  - pymdownx.details           # Collapsible "Answer" blocks
  - pymdownx.superfences       # Better code blocks
  - pymdownx.tabbed:           # Tabbed content for different OS instructions
      alternate_style: true 
  - attr_list                  # For image alignment
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink

extra_css:
  - stylesheets/extra.css

repo_name: HpoWorkshop
repo_url: https://github.com/P2GX/HpoWorkshop

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

not_in_nav: |
  phenotyping/encoding-answers.md
  phenotyping/hpo-answers.md

nav:
  - Home: index.md
  - 1. Introduction:
      - Overview: introduction/index.md
      - Background Reading: introduction/reading.md
      - What is an ontology?: introduction/ontology.md
  - 2. Clinical Phenotyping:
      - Navigating the HPO website: phenotyping/hpobrowser.md
      - HPO Browsers: phenotyping/browsers.md
      - Encoding Clinical Data: phenotyping/encoding.md
  - 3. Phenopackets:
      - Overview: phenopackets/index.md
      - Phenoboard: phenopackets/phenoboard.md
      - Example: phenopackets/example.md
  - 4. Exomiser:
      - Overview: exomiser/index.md
      - Command line: exomiser/cmdline.md
      - Settings: exomiser/settings.md
      - Running Exomiser: exomiser/running.md
